# Generated by Django 4.0.1 on 2022-01-15 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPorfolio',
            new_name='UserPortfolio',
        ),
    ]
